gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Avimon!\p"
		.string "My name is BIRD.\p"
	.string "But everyone calls me the Avimon\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call an “Avimon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Avimon.\p"
	.string "We humans live alongside Avimon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and clash with others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Avimon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Avimon.\p"
	.string "To unravel Avimon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own migration is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Avimon where dreams,\l"
	.string "flight paths, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come spot me in my Avimon LAB.\p"
	.string "$"
