gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2} for your field kit!$"

gText_TheBagIsFull::
	.string "The BAG is full of field supplies…$"

gText_PutItemInPocket::
	.string "{PLAYER} packed the {STR_VAR_2}\n"
	.string "into the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} spotted one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full of field supplies…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} packed the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2} for your roost!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2} for fieldwork!$"

gText_PlayerFoundItems::
	.string "{PLAYER} spotted {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} stowed the COINS in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} spotted\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} spotted\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
