gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the AVIMON CENTER.\p"
	.string "We restore your tired AVIMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your AVIMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your AVIMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your AVIMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the AVIMON CENTER.\p"
	.string "We restore your tired AVIMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several BIRD KEEPERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first BIRD KEEPER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your AVIMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your AVIMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
